- block:
    - name: Install test suite
      yum:
        name: test-suite-ohpc
        state: latest

    - name: Configure test suite
      shell: cd /home/ohpc-test/tests &&  ./configure --disable-papi  --disable-likwid  --enable-fftw  --enable-scotch  --enable-boost  --enable-boost-mpi  --enable-ptscotch  --enable-openblas  --enable-plasma  --enable-packaging  --with-mpi-families=openmpi3  --with-compiler-families=gnu7  && make check
      become: yes
      become_user: ohpc-test
      become_method: su
      register: testsuite_output

    - debug: msg="{{ testsuite_output.stdout_lines }} {{ testsuite_output.stderr_lines }}"

  when:
    - inventory_hostname in groups[nt_sms]
    - enable_testsuiteohpc == True
